Repository TokTok/website, pull requests merged in 2021-12, with the labels that each got.

#250 chore: Delete travis; add GitHub workflow.
  .github/settings.yml
  .github/workflows/ci.yml
  .hadolint.yaml
  .travis.yml
  Dockerfile
  Makefile
  entrypoint.sh
  heroku.yml
  netlify.toml
Labels: chore

#251 chore: Don't build docs for ruby extensions.
  .github/settings.yml
  Dockerfile
Labels: chore

#248 docs: Change Antidote repo link
  .restyled.yaml
  toktok/integrations.md
Labels: documentation

#245 cleanup: Remove references to Jenkins
  toktok/_data/jenkins.yml
  toktok/repos.md
Labels: cleanup

#153 docs: Added more Android clients
  toktok/integrations.md
Labels: documentation

#155 docs: add actual rust bindings to integrations page.
  toktok/integrations.md
Labels: documentation

#253 chore: Only git pull if .git exists.
  Makefile
Labels: chore

#254 chore: Only git pull if we're on a branch.
  Makefile
Labels: chore

#255 docs: Move #toktok to LiberaChat
  toktok/index.md
Labels: documentation
